/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Paquete;
import utilitario.funcionesPanelDetallePaquete;

/**
 *
 * @author a20090245
 */
public class panelDetallePaquete extends javax.swing.JPanel {
    private String usuario;
    private String contrasenha;
    private String tipoUsuario;
    
    public panelDetallePaquete() {
        initComponents();
    }
    
    public panelDetallePaquete(String numeroRastreo, String usuario, String contrasenha, String tipoUsuario) throws InstantiationException, IllegalAccessException {
        initComponents();
        this.setVisible(true);
        
        this.usuario = usuario;
        this.contrasenha = contrasenha;
        this.tipoUsuario = tipoUsuario;
        
        funcionesPanelDetallePaquete fuDetallePaquete = new funcionesPanelDetallePaquete();
        Paquete paquete = fuDetallePaquete.devolverDescripcionGeneralPaquete(numeroRastreo);
        
        this.tituloRastreoLabel.setText("Detalle de envio: " + numeroRastreo);
        this.lugarOrigenTextField.setText(paquete.getAlmacenOrigen().getCiudad());
        this.lugarDestinoTextField.setText(paquete.getAlamcenDestino().getCiudad());
        String sFechaEnvio = fuDetallePaquete.convertirStringFecha(paquete.getFechaEnvio());
        String sFechaRecepcion = fuDetallePaquete.convertirStringFecha(paquete.getFechaRecepcion());
        this.fechaSalidaTextField.setText(sFechaEnvio);
        this.fechaLlegadaTextField.setText(sFechaRecepcion);
        this.estadoPaqueteTextField.setText(fuDetallePaquete.devolverEstadoPaquete(paquete.getEstado()));
        this.DesciprcionTextField.setText(paquete.getDescripcion());
        
        fuDetallePaquete.colocarCampoComoNoEditable(lugarOrigenTextField);
        fuDetallePaquete.colocarCampoComoNoEditable(lugarDestinoTextField);
        fuDetallePaquete.colocarCampoComoNoEditable(fechaSalidaTextField);
        fuDetallePaquete.colocarCampoComoNoEditable(fechaLlegadaTextField);
        fuDetallePaquete.colocarCampoComoNoEditable(estadoPaqueteTextField);
        fuDetallePaquete.colocarCampoComoNoEditable(DesciprcionTextField);
        
        List<String[]> listadoPaquetes = fuDetallePaquete.devolverDetallePaquete(numeroRastreo);
        
        fuDetallePaquete.mostrarDetallePaquete(listadoPaquetes,this.detallePaqueteTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        detallePaqueteTabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lugarOrigenTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lugarDestinoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaSalidaTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechaLlegadaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        estadoPaqueteTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DesciprcionTextField = new javax.swing.JTextField();
        regresarBoton = new javax.swing.JButton();
        tituloRastreoLabel = new javax.swing.JLabel();

        detallePaqueteTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro de Rastreo", "Estado", "Destinatario", "País Destino", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(detallePaqueteTabla);

        jPanel2.setBackground(new java.awt.Color(193, 189, 189));

        jLabel5.setText("Lugar de Origen:");

        jLabel6.setText("Lugar de Destino:");

        jLabel7.setText("Fecha de Salida:");

        jLabel8.setText("Fecha de Llegada:");

        jLabel9.setText("Estado:");

        jLabel11.setText("Descripción:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fechaLlegadaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechaSalidaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lugarDestinoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lugarOrigenTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estadoPaqueteTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DesciprcionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lugarOrigenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lugarDestinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaSalidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaLlegadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoPaqueteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DesciprcionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        regresarBoton.setText("Regresar");
        regresarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarBotonMouseClicked(evt);
            }
        });

        tituloRastreoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tituloRastreoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regresarBoton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloRastreoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regresarBoton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarBotonMouseClicked
        // TODO add your handling code here:
        panelPaqueteBusqueda pnlPaqueteBusqueda;
        try {
            pnlPaqueteBusqueda = new panelPaqueteBusqueda(getUsuario(),getContrasenha(),getTipoUsuario());
                    
            VentanaPrincipal.pnlFondo.removeAll();
            VentanaPrincipal.pnlFondo.add(pnlPaqueteBusqueda,BorderLayout.CENTER);
            VentanaPrincipal.pnlFondo.revalidate();
            VentanaPrincipal.pnlFondo.repaint();
        } catch (InstantiationException ex) {
            Logger.getLogger(panelDetallePaquete.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(panelDetallePaquete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_regresarBotonMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DesciprcionTextField;
    private javax.swing.JTable detallePaqueteTabla;
    private javax.swing.JTextField estadoPaqueteTextField;
    private javax.swing.JTextField fechaLlegadaTextField;
    private javax.swing.JTextField fechaSalidaTextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lugarDestinoTextField;
    private javax.swing.JTextField lugarOrigenTextField;
    private javax.swing.JButton regresarBoton;
    private javax.swing.JLabel tituloRastreoLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the contrasenha
     */
    public String getContrasenha() {
        return contrasenha;
    }

    /**
     * @param contrasenha the contrasenha to set
     */
    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }

    /**
     * @return the tipoUsuario
     */
    public String getTipoUsuario() {
        return tipoUsuario;
    }

    /**
     * @param tipoUsuario the tipoUsuario to set
     */
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
}
